config smartdns
	option server_name 'cn'
	option port '6053'
	option tcp_server '1'
	option ipv6_server '1'
	option prefetch_domain '1'
	option redirect 'none'
	option cache_size '0'
	option rr_ttl_min '300'
	option rr_ttl_max '3600'
	option seconddns_port '6553'
	option seconddns_tcp_server '1'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option force_aaaa_soa '0'
	option coredump '0'
	option seconddns_no_cache '1'
	option serve_expired '1'
	option dualstack_ip_selection '1'
	option seconddns_no_dualstack_selection '0'
	option seconddns_no_speed_check '0'
	option enabled '1'
	option seconddns_enabled '1'
	option seconddns_server_group 'global'
	list old_redirect 'none'
	list old_port '6053'
	list old_enabled '1'

config server
	option type 'udp'
	option name 'Ali ipv4-1'
	option ip '223.5.5.5'
	option port '53'
	option server_group 'home'
	option blacklist_ip '0'
	option enabled '1'
	
config server
	option type 'udp'
	option name 'Ali ipv4-2'
	option ip '223.6.6.6'
	option port '53'
	option server_group 'home'
	option blacklist_ip '0'
	option enabled '1'	

config server
	option name 'Ali https'
	option type 'https'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option addition_arg 'nameserver /dns.alidns.com/[home]'
	option server_group 'cn'
	option port '443'
	option ip 'dns.alidns.com/dns-query'
	option enabled '1'

config server
	option name 'Ali tls'
	option ip 'dns.alidns.com'
	option port '853'
	option type 'tls'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option addition_arg 'nameserver /dns.alidns.com/[home]'
	option server_group 'cn'
	option enabled '1'

config server
	option type 'udp'
	option name 'Ali ipv6'
	option ip '2400:3200::1'
	option port '53'
	option server_group 'cn'
	option blacklist_ip '0'
	option enabled '1'

config server
	option type 'udp'
	option name 'CFIEC ipv6'
	option ip '240C::6666'
	option port '53'
	option server_group 'cn'
	option blacklist_ip '0'
	option enabled '1'

config server
	option type 'udp'
	option name 'Google ipv4'
	option ip '8.8.8.8'
	option port '53'
	option server_group 'foreign'
	option blacklist_ip '0'
	option enabled '1'

config server
	option name 'Google https'
	option type 'https'
	option no_check_certificate '0'
	option server_group 'global'
	option blacklist_ip '0'
	option addition_arg 'nameserver /dns.google/[foreign]'
	option port '443'
	option ip 'dns.google/dns-query'
	option enabled '1'

config server
	option name 'Google tls'
	option ip 'dns.google'
	option port '853'
	option type 'tls'
	option no_check_certificate '0'
	option server_group 'global'
	option blacklist_ip '0'
	option addition_arg 'nameserver /dns.google/[foreign]'
	option enabled '1'

config server
	option type 'udp'
	option name 'Google ipv6'
	option ip '2001:4860:4860::8888'
	option port '53'
	option server_group 'global'
	option blacklist_ip '0'
	option enabled '1'

config server
	option type 'udp'
	option name 'Cloudflare ipv4'
	option port '53'
	option blacklist_ip '0'
	option server_group 'foreign'
	option ip '1.1.1.1'
	option enabled '1'

config server
	option name 'Cloudflare https'
	option ip 'dns.cloudflare.com/dns-query'
	option type 'https'
	option no_check_certificate '0'
	option server_group 'global'
	option blacklist_ip '0'
	option addition_arg 'nameserver /dns.cloudflare.com/[foreign]'
	option port '443'
	option enabled '1'

config server
	option name 'Cloudflare tls'
	option port '853'
	option type 'tls'
	option no_check_certificate '0'
	option server_group 'global'
	option blacklist_ip '0'
	option enabled '1'
	option ip '1.1.1.1'

config server
	option enabled '1'
	option type 'udp'
	option name 'Cloudflare ipv6'
	option ip '2606:4700:4700::1111'
	option port '53'
	option server_group 'global'
	option blacklist_ip '0'
